// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<domain.Config>;

export function IsConnected():Promise<boolean>;

export function SaveConfig(arg1:domain.Config):Promise<void>;
